import type { Crop, Family } from "./types";

export const FAMILIES: { id: Family; name: string; color: string }[] = [
  { id: "cereal", name: "Cereal", color: "#fcd34d" },
  { id: "legume", name: "Legume", color: "#4ade80" },
  { id: "brassica", name: "Brassica", color: "#a78bfa" },
  { id: "solanaceous", name: "Solanaceous", color: "#fb923c" },
  { id: "oilseed", name: "Oilseed", color: "#fbbf24" },
  { id: "grass", name: "Grass / Cover", color: "#86efac" },
  { id: "allium", name: "Allium", color: "#e2e8f0" },
];

export const familyName = (f: Family): string =>
  FAMILIES.find((x) => x.id === f)?.name ?? f;

export const familyColor = (f: Family): string =>
  FAMILIES.find((x) => x.id === f)?.color ?? "#94a3b8";

export const CROPS: Crop[] = [
  {
    id: "corn",
    name: "Corn",
    tone: "#fbbf24",
    family: "cereal",
    coverCrop: false,
    n: -10,
    p: -7,
    k: -5,
    om: 1.6,
    roots: 1.2,
    yieldBase: 1.0,
    sensitivity: { n: 0.5, p: 0.3, k: 0.2 },
    water: 0.85,
    texture: 0.55,
    diseaseBreak: 0,
  },
  {
    id: "wheat",
    name: "Wheat",
    tone: "#eab308",
    family: "cereal",
    coverCrop: false,
    n: -9,
    p: -4,
    k: -4,
    om: 2.4,
    roots: 1.8,
    yieldBase: 0.9,
    sensitivity: { n: 0.5, p: 0.25, k: 0.25 },
    water: 0.7,
    texture: 0.5,
    diseaseBreak: 0,
  },
  {
    id: "oats",
    name: "Oats",
    tone: "#d9b93f",
    family: "cereal",
    coverCrop: false,
    n: -7,
    p: -3,
    k: -4,
    om: 2.6,
    roots: 2.2,
    yieldBase: 0.88,
    sensitivity: { n: 0.5, p: 0.25, k: 0.25 },
    water: 0.6,
    texture: 0.5,
    diseaseBreak: 0,
  },
  {
    id: "soybean",
    name: "Soybean",
    tone: "#4ade80",
    family: "legume",
    coverCrop: false,
    n: 6,
    p: -2,
    k: -4,
    om: 2.4,
    roots: 1.6,
    yieldBase: 0.83,
    sensitivity: { n: 0.35, p: 0.3, k: 0.35 },
    water: 0.75,
    texture: 0.55,
    diseaseBreak: 0,
  },
  {
    id: "peas",
    name: "Peas",
    tone: "#22c55e",
    family: "legume",
    coverCrop: false,
    n: 7,
    p: -2,
    k: -3,
    om: 1.8,
    roots: 1.2,
    yieldBase: 0.8,
    sensitivity: { n: 0.3, p: 0.35, k: 0.35 },
    water: 0.6,
    texture: 0.45,
    diseaseBreak: 0,
  },
  {
    id: "alfalfa",
    name: "Alfalfa",
    tone: "#16a34a",
    family: "legume",
    coverCrop: false,
    n: 10,
    p: -6,
    k: -9,
    om: 3.5,
    roots: 3.0,
    yieldBase: 0.78,
    sensitivity: { n: 0.6, p: 0.2, k: 0.2 },
    water: 0.8,
    texture: 0.6,
    diseaseBreak: 0,
  },
  {
    id: "canola",
    name: "Canola",
    tone: "#a16207",
    family: "brassica",
    coverCrop: false,
    n: -5,
    p: -3,
    k: -5,
    om: 2.4,
    roots: 2.0,
    yieldBase: 0.8,
    sensitivity: { n: 0.5, p: 0.3, k: 0.2 },
    water: 0.7,
    texture: 0.5,
    diseaseBreak: 0.25,
  },
  {
    id: "radish",
    name: "Cover Radish",
    tone: "#c084fc",
    family: "brassica",
    coverCrop: true,
    n: -2,
    p: -1,
    k: -2,
    om: 3.0,
    roots: 3.0,
    yieldBase: 0.35,
    sensitivity: { n: 0.2, p: 0.4, k: 0.4 },
    water: 0.4,
    texture: 0.35,
    diseaseBreak: 0.5,
  },
  {
    id: "rye",
    name: "Cereal Rye",
    tone: "#86efac",
    family: "grass",
    coverCrop: true,
    n: -3,
    p: -1,
    k: -2,
    om: 4.0,
    roots: 3.2,
    yieldBase: 0.38,
    sensitivity: { n: 0.4, p: 0.3, k: 0.3 },
    water: 0.5,
    texture: 0.4,
    diseaseBreak: 0,
  },
  {
    id: "potato",
    name: "Potato",
    tone: "#fb923c",
    family: "solanaceous",
    coverCrop: false,
    n: -11,
    p: -8,
    k: -14,
    om: 0.7,
    roots: 0.4,
    yieldBase: 1.12,
    sensitivity: { n: 0.35, p: 0.25, k: 0.4 },
    water: 0.8,
    texture: 0.3,
    diseaseBreak: 0,
  },
  {
    id: "sunflower",
    name: "Sunflower",
    tone: "#f59e0b",
    family: "oilseed",
    coverCrop: false,
    n: -9,
    p: -6,
    k: -9,
    om: 1.8,
    roots: 2.4,
    yieldBase: 0.95,
    sensitivity: { n: 0.4, p: 0.3, k: 0.3 },
    water: 0.55,
    texture: 0.45,
    diseaseBreak: 0.15,
  },
  {
    id: "onion",
    name: "Onion",
    tone: "#e2e8f0",
    family: "allium",
    coverCrop: false,
    n: -9,
    p: -5,
    k: -7,
    om: 1.2,
    roots: 0.6,
    yieldBase: 0.9,
    sensitivity: { n: 0.4, p: 0.3, k: 0.3 },
    water: 0.7,
    texture: 0.45,
    diseaseBreak: 0,
  },
];

export const cropById = (id: string): Crop =>
  CROPS.find((c) => c.id === id) ?? CROPS[0];

export const cashCrops = CROPS.filter((c) => !c.coverCrop);